// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_auth_send_link from "./routes/api/auth/send-link.ts";
import * as $auth_verify from "./routes/auth/verify.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $stremio_path_ from "./routes/stremio/[...path].ts";
import * as $EmailLinkForm from "./islands/EmailLinkForm.tsx";
import * as $LoginForm from "./islands/LoginForm.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/auth/send-link.ts": $api_auth_send_link,
    "./routes/auth/verify.tsx": $auth_verify,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/stremio/[...path].ts": $stremio_path_,
  },
  islands: {
    "./islands/EmailLinkForm.tsx": $EmailLinkForm,
    "./islands/LoginForm.tsx": $LoginForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
