// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_auth_login_or_signup from "./routes/api/auth/login-or-signup.ts";
import * as $api_auth_login_with_password from "./routes/api/auth/login-with-password.ts";
import * as $api_auth_request_password_reset from "./routes/api/auth/request-password-reset.ts";
import * as $api_auth_reset_password from "./routes/api/auth/reset-password.ts";
import * as $api_auth_send_login_code from "./routes/api/auth/send-login-code.ts";
import * as $api_auth_signup from "./routes/api/auth/signup.ts";
import * as $api_auth_verify_code from "./routes/api/auth/verify-code.ts";
import * as $api_profiles_id_ from "./routes/api/profiles/[id].ts";
import * as $api_profiles_index from "./routes/api/profiles/index.ts";
import * as $api_sessions from "./routes/api/sessions.ts";
import * as $api_test_email from "./routes/api/test-email.ts";
import * as $api_tmdb_key from "./routes/api/tmdb-key.ts";
import * as $auth_code from "./routes/auth/code.tsx";
import * as $auth_password from "./routes/auth/password.tsx";
import * as $auth_reset from "./routes/auth/reset.tsx";
import * as $auth_signup_success from "./routes/auth/signup-success.tsx";
import * as $auth_verify from "./routes/auth/verify.tsx";
import * as $health from "./routes/health.ts";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.ts";
import * as $player_profileId_ from "./routes/player/[profileId].tsx";
import * as $profiles from "./routes/profiles.tsx";
import * as $settings from "./routes/settings.tsx";
import * as $stremio_path_ from "./routes/stremio/[...path].ts";
import * as $Auth_CodeInputForm from "./islands/Auth/CodeInputForm.tsx";
import * as $Auth_EmailLinkForm from "./islands/Auth/EmailLinkForm.tsx";
import * as $Auth_PasswordLoginForm from "./islands/Auth/PasswordLoginForm.tsx";
import * as $Auth_ResetPasswordForm from "./islands/Auth/ResetPasswordForm.tsx";
import * as $ProfileManager_DesktopProfileManager from "./islands/ProfileManager/DesktopProfileManager.tsx";
import * as $ProfileManager_MobileProfileManager from "./islands/ProfileManager/MobileProfileManager.tsx";
import * as $ProfileManager_ProfileManager from "./islands/ProfileManager/ProfileManager.tsx";
import * as $SettingsModal from "./islands/SettingsModal.tsx";
import * as $StremioFrame from "./islands/StremioFrame.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/auth/login-or-signup.ts": $api_auth_login_or_signup,
    "./routes/api/auth/login-with-password.ts": $api_auth_login_with_password,
    "./routes/api/auth/request-password-reset.ts":
      $api_auth_request_password_reset,
    "./routes/api/auth/reset-password.ts": $api_auth_reset_password,
    "./routes/api/auth/send-login-code.ts": $api_auth_send_login_code,
    "./routes/api/auth/signup.ts": $api_auth_signup,
    "./routes/api/auth/verify-code.ts": $api_auth_verify_code,
    "./routes/api/profiles/[id].ts": $api_profiles_id_,
    "./routes/api/profiles/index.ts": $api_profiles_index,
    "./routes/api/sessions.ts": $api_sessions,
    "./routes/api/test-email.ts": $api_test_email,
    "./routes/api/tmdb-key.ts": $api_tmdb_key,
    "./routes/auth/code.tsx": $auth_code,
    "./routes/auth/password.tsx": $auth_password,
    "./routes/auth/reset.tsx": $auth_reset,
    "./routes/auth/signup-success.tsx": $auth_signup_success,
    "./routes/auth/verify.tsx": $auth_verify,
    "./routes/health.ts": $health,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/logout.ts": $logout,
    "./routes/player/[profileId].tsx": $player_profileId_,
    "./routes/profiles.tsx": $profiles,
    "./routes/settings.tsx": $settings,
    "./routes/stremio/[...path].ts": $stremio_path_,
  },
  islands: {
    "./islands/Auth/CodeInputForm.tsx": $Auth_CodeInputForm,
    "./islands/Auth/EmailLinkForm.tsx": $Auth_EmailLinkForm,
    "./islands/Auth/PasswordLoginForm.tsx": $Auth_PasswordLoginForm,
    "./islands/Auth/ResetPasswordForm.tsx": $Auth_ResetPasswordForm,
    "./islands/ProfileManager/DesktopProfileManager.tsx":
      $ProfileManager_DesktopProfileManager,
    "./islands/ProfileManager/MobileProfileManager.tsx":
      $ProfileManager_MobileProfileManager,
    "./islands/ProfileManager/ProfileManager.tsx":
      $ProfileManager_ProfileManager,
    "./islands/SettingsModal.tsx": $SettingsModal,
    "./islands/StremioFrame.tsx": $StremioFrame,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
