name: Build and Release Android APK

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag for the new release (e.g., v1.0.1)'
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create a release

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install PWABuilder CLI
        run: npm install -g @pwabuilder/cli

      - name: Generate APK with PWABuilder CLI
        run: pwabuilder https://zentrio.eu -p android -d .

      - name: Create Release and Upload APK
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.event.inputs.tag }}
        run: |
          gh release create "$TAG_NAME" \
            --repo "$GITHUB_REPOSITORY" \
            --title "Release $TAG_NAME" \
            --notes "Automated APK release for $TAG_NAME" \
            ./Zentrio.apk