name: Build and Release Android APK

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag for the new release (e.g., v1.0.1)'
        required: true
        type: string

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create a release and upload assets

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Generate APK via PWABuilder API
        run: |
          curl -X POST "https://prod.pwabuilder.com/api/build/package" \
          -H "Content-Type: application/json" \
          -d '{"url": "https://zentrio.eu", "platforms": ["android"]}' \
          -o android.zip

      - name: Unzip Generated Project
        run: unzip android.zip -d android_project

      - name: Find Generated APK
        id: find_apk
        run: echo "apk_path=$(find android_project -name '*.apk' -print -quit)" >> $GITHUB_OUTPUT

      - name: Create Release and Upload APK
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.event.inputs.tag }}
        run: |
          if [ -z "${{ steps.find_apk.outputs.apk_path }}" ]; then
            echo "Error: APK file not found after build."
            exit 1
          fi
          gh release create "$TAG_NAME" \
            --repo "$GITHUB_REPOSITORY" \
            --title "Release $TAG_NAME" \
            --notes "Automated APK release for $TAG_NAME" \
            "${{ steps.find_apk.outputs.apk_path }}"