# .github/workflows/firebase-hosting-merge.yml

name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Replace Firebase Config
        run: |
          awk -v config="${{ secrets.FIREBASE_CONFIG }}" '{gsub(/const firebaseConfig = __FIREBASE_CONFIG__;/, "const firebaseConfig = " config ";")}1' public/app.js > app.js.tmp && mv app.js.tmp public/app.js
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_STREMIOHUB_EE185 }}
          channelId: live
          projectId: stremiohub-ee185