name: Deploy to Firebase on PR
'on': pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Replace Firebase Config in Hosting
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: |
          # Extracts the JSON object, even if it's inside a JS variable
          CONFIG_STRING=$(echo "$FIREBASE_CONFIG" | tr -d '\n\r' | grep -o '{.*}' | sed 's/;$//')
          sed -i "s|__FIREBASE_CONFIG__|${CONFIG_STRING}|g" public/app.js

      - name: Install Function Dependencies
        run: npm --prefix functions install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools
        
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_STREMIOHUB_EE185 }}'

      - name: Deploy to Firebase Preview Channel
        run: firebase deploy --only functions,hosting --project stremiohub-ee185 --non-interactive --token "$GCLOUD_ACCESS_TOKEN" --force